<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE ciudades [
    <!ELEMENT ciudades (ciudad)>
    <!ELEMENT ciudad (nombre, pais)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ATTLIST pais continente CDATA #IMPLIED>
]>

<ciudades xmlns="">
    <ciudad>
        <nombre>Nueva Delhi</nombre>
        <pais continente="Ásia">India</pais>
    </ciudad>
    <ciudad>
        <nombre>Lisboa</nombre>
        <pais continente="Europa">Portugal</pais>
    </ciudad>
    <ciudad>
        <nombre>El Cairo</nombre>
        <pais continente="África">Egipto</pais>
    </ciudad>
</ciudades>